blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('blogposts/', views.BlogPostView.as_view(), name='blogposts'),
    path('blogpost/<int:pk>', views.BlogPostDetailView.as_view(), name='blog-post-detail'),
    path('authors/', views.AuthorsListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('blogpost/<int:pk>/comment/', views.CommentCreateView.as_view(), name='blog_comment')
]

blogspace/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.urls import include

urlpatterns += [
    path('blog/', include('blog.urls')),
]

from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='blog/', permanent=True)),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

blog/models.py
from tkinter import CASCADE
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """Model representing a blog topic."""
    name = models.CharField(max_length=200, help_text='Enter a blog topic (e.g Technology')

    def __str__(self):
        """String for representing the Model Object."""
        return self.name

class BlogPost(models.Model):
    """Model representing a blog post."""
    title = models.CharField(max_length=200)
    post_date = models.DateField(auto_now_add=True)
    # A blog post may only have one author but many authors can have many blog posts
    author = models.ForeignKey('Author', on_delete=models.CASCADE)
    # A text field that holds the contents of our blog post
    description = models.TextField(max_length=1000, help_text='Enter a description for you post')
    # A Blog Post can have many topics and a topic can be applied to many blog posts
    topic = models.ManyToManyField(Topic, help_text='Select a topic for this blog post')

    class Meta:
        # order the blog posts in reverse cronological order
        ordering = ['-post_date']
    
    def __str__(self):
        """String for representing the Model object."""
        return f'{self.title} - {self.user.username}'
    
    def get_absolute_url(self):
        """Returns the URL to access a detail record for this post."""
        return reverse('blog-post-detail', args=[str(self.id)])

class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    bio = models.TextField(max_length=1000, help_text='Enter a biography')

    class Meta:
        ordering=['user']

    def __str__(self):
        """String for representing Author object."""
        return self.user.username
    
    def get_absolute_url(self):
        """Returns the URL to access a deatil record for this user."""
        return reverse('author-detail', args=[str(self.id)])

class Comment(models.Model):
    # Every comment must have an Author and Authors can have many comments
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    post_date = models.DateTimeField(auto_now_add=True)
    # A text field of what comment is 
    description = models.TextField(max_length=1000, help_text='Enter comment about blog here')
    # A blog post the comment refers too
    blogpost =models.ForeignKey(BlogPost, on_delete=models.CASCADE)

    class Meta:
        # order the comments in cronological order according to post date
        ordering=['post_date']
    
    def __str__(self):
        """String for representing Comment object."""
        return f'{self.blogpost.title} - {self.description}'

blog/views.py
from django.shortcuts import render
from .models import Topic, BlogPost, Author, Comment
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.urls import reverse
from django.shortcuts import get_object_or_404

def index(request):
    """View function for home page of site."""

    num_blogposts = BlogPost.objects.count()
    num_authors = Author.objects.count()
    num_comments = Comment.objects.count()
    num_topics = Topic.objects.count()
    
    context = {
        'num_blogposts': num_blogposts,
        'num_authors': num_authors,
        'num_comments': num_comments,
        'num_topics': num_topics,
    }

    return render(request, 'index.html', context=context)

class BlogPostView(generic.ListView):
    model = BlogPost
    paginate_by = 10

class BlogPostDetailView(generic.DetailView):
    model = BlogPost

class AuthorsListView(generic.ListView):
    model = Author
    paginate_by = 10

class AuthorDetailView(generic.DetailView):
    model = Author

class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['description']

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(CommentCreateView, self).get_context_data(**kwargs)
        # Get the blogger object from the "pk" URL parameter and add it to the context
        context['blogpost'] = get_object_or_404(BlogPost, pk = self.kwargs['pk'])
        return context

    def form_valid(self, form):
        """
        Add author and associated blog to form data before setting it as valid (so it is saved to model)
        """
        #Add logged-in user as author of comment
        form.instance.author = self.request.user
        #Associate comment with blog based on passed id
        form.instance.blogpost=get_object_or_404(BlogPost, pk = self.kwargs['pk'])
        # Call super-class form validation behaviour
        return super(CommentCreateView, self).form_valid(form)

    def get_success_url(self): 
        """
        After posting comment return to associated blog.
        """
        return reverse('blog-post-detail', kwargs={'pk': self.kwargs['pk'],})

blog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>JT's blog</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'blogposts' %}">All posts</a></li>
          <li><a href="{% url 'authors' %}">All authors</a></li>
        </ul>
        <ul class="sidebar-nav">
         {% if user.is_authenticated %}
           <li>User: {{ user.get_username }}</li>
           <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
         {% else %}
           <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
         {% endif %}
        </ul>      
     {% endblock %}
     {% block pagination %}
     {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
    {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

blog/templates/blog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Blogger: {{ author.user }}</h1>
    <h3>Bio</h3>
    <p>{{ author.bio }}</p>
    <h3>Blogs list</h3>
    <ul>
        {% for post in author.blogpost_set.all %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a> ({{ post.post_date }})
        </li>
        {% endfor %}
      </ul>
{% endblock %}

blog/templates/blog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
 <h1>All bloggers</h1>
 {% if author_list %}
 <ul>
     {% for author in author_list %}
     <li>
         <a href="{{ author.get_absolute_url }}">{{ author.user }}</a>
     </li>
     {% endfor %}
 </ul>
 {% else %}
    <p>There are no books in the library.</p>
 {% endif %}
{% endblock %}

blog/templates/blog/blogpost_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ blogpost.title }}</h1>

  <p><strong>Post date</strong> {{ blogpost.post_date }}</p>
  <p><strong>Author:</strong> <a href="{{ blogpost.author.get_absolute_url }}">{{ blogpost.author }}</a></p> 
  <p><strong>Description:</strong> <br><br> {{ blogpost.description }}</p>
  <p><strong>Topic:</strong> {{ blogpost.topic.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Comments</h4>

    {% for comment in blogpost.comment_set.all %}
      <hr>
      <p>{{ comment.author }} ({{ comment.post_date }}) - {{ comment.description}}</p>
    {% endfor %}
    <hr>
    {% if user.is_authenticated %}
      <a href="{% url 'blog_comment' blogpost.id %}">Add a new comment</a></p>
    {% else %}
      <p><a href="{% url 'login'%}?next={{request.path}}">Login</a> to add a new comment</p>
    {% endif %} 
  </div>
{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Blog Post List</h1>
  {% if blogpost_list %}
  <ul>
    {% for post in blogpost_list %}
      <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a> ({{post.post_date}}) - <a href="{{ post.author.get_absolute_url }}">{{ post.author }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no posts in the blog.</p>
  {% endif %}
{% endblock %}

blog/templates/blog/comment_form.html
{% extends "base_generic.html" %}

{% block content %}
<p>Post your comment for: <a href="{% url 'blog-post-detail' blogpost.pk %}">{{blogpost.title}}</a></p>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

path('blog/<int:pk>', views.BlogDetailView.as_view(), name='blog-detail'),

blog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Jorge Tadeo's blog</h1>
  <p>Welcome to my blog, a website developed by <em>me</em>!</p>
  <h2>Blog content</h2>
  <p>The blog has the following record counts:</p>
  <ul>
    <li><strong>Blog Posts:</strong> {{ num_blogposts }}</li>
    <li><strong>Total comments:</strong> {{ num_comments }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>Topics:</strong> {{ num_topics }}</li>
  </ul>
{% endblock %}